development:
  adapter: inline

test:
  adapter: inline

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: circumcentral_rails_production
