default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: circumcentral_rails_development
  username: circumcentral
  password: password

test:
  <<: *default
  database: circumcentral_rails_test

production:
  <<: *default
  database: circumcenter_production
  username: circumcenter
  password: <%= ENV['CIRCUMCENTER_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
